name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.5.1]

    steps:
    - name: "Checkout Repository"
      uses: actions/checkout@v3

    - name: "Install Dependencies"
      run: npm install

    - name: "Build Application"
      run: npm run build

    - name: "Publish Artifact"
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: dist
